# Generated by Django 5.2.7 on 2025-10-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('ingredients', models.TextField(verbose_name='Продукты')),
                ('recipe', models.TextField(verbose_name='Рецепт')),
                ('gluten_free', models.BooleanField(default=False, verbose_name='Без глютена')),
                ('vegan', models.BooleanField(default=False, verbose_name='Веганское')),
                ('eco', models.BooleanField(default=False, verbose_name='ЭКО')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('chat_id', models.CharField(max_length=50)),
            ],
        ),
    ]
