# Generated by Django 5.2.7 on 2025-10-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название блюда'),
        ),
    ]
