# Generated by Django 5.2.7 on 2025-10-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_alter_dish_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена за 100 грамм')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('title',), 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('user_name',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(blank=True, null=True, verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='DishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Масса в граммах')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dish', to='datacenter.dish', verbose_name='Блюдо')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт и цена',
                'verbose_name_plural': 'Продукты и цена',
                'ordering': ('dish',),
            },
        ),
    ]
