# Generated by Django 5.2.7 on 2025-10-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0003_product_alter_dish_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Примечание'),
        ),
    ]
