# Generated by Django 5.2.7 on 2025-10-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0004_product_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishproduct',
            name='note',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Примечание'),
        ),
    ]
