# Generated by Django 5.2.7 on 2025-10-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0005_dishproduct_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='note',
        ),
    ]
