# Generated by Django 5.2.7 on 2025-10-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0006_remove_product_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='dishproduct',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Масса в граммах'),
        ),
    ]
