# Generated by Django 5.2.7 on 2025-10-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0007_remove_dish_ingredients_alter_dishproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Масса в граммах'),
        ),
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.PositiveIntegerField(default=2147483647, verbose_name='Цена'),
        ),
    ]
